# PyTorch Basics

In [3]:
from utils import *

Create a *random* tensor in PyTorch with `torch.Tensor`

In [4]:
import torch
new_tensor = torch.Tensor(2, 3)
describe(new_tensor)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0.0000e+00, 1.5414e-43, 1.8754e+28],
        [2.0110e+20, 2.6807e-09, 1.0357e-11]])


Create a tensor with values from a uniform distribution on interval [0, 1)

In [5]:
import torch
new_tensor = torch.rand(2, 3)
describe(new_tensor)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0.0941, 0.1576, 0.5028],
        [0.2901, 0.2117, 0.7646]])


Create tensors all filled with the same scalar.

In [6]:
import torch
tensor_with_same_scalar = torch.zeros(2, 3)
describe(tensor_with_same_scalar)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


To create tensors filled with all zeros and ones, use the built-in functions.  
To create tnesors filled scalar other than zero or one, user `fill_()` method.  
In PyTorch, mathods with a underscore refers to an **in-place** operation

In [9]:
import torch
tensor_with_same_scalar.fill_(100)
describe(tensor_with_same_scalar)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[100., 100., 100.],
        [100., 100., 100.]])


Create a tensor from lists.

In [10]:
import torch
new_tensor = torch.Tensor([[1, 2, 3],
                           [4, 5, 6]])
describe(new_tensor)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Create a tensor from NumPy array.  
Note: It results in type `DoubleTensor` instead of the default `FloatTensor`

In [11]:
import numpy as np
import torch
np_arr = np.random.rand(2, 3)
new_tensor = torch.from_numpy(np_arr)
describe(new_tensor)

type: torch.DoubleTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0.5394, 0.5647, 0.0429],
        [0.3226, 0.3163, 0.9123]], dtype=torch.float64)


Create a tensor in a specific type, such as `float`, `long`, `double`, etc

In [12]:
import torch
new_float_tensor = torch.FloatTensor([[1, 2, 3],
                                      [4, 5, 6]])
describe(new_float_tensor)

type: torch.FloatTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
new_long_tensor = new_float_tensor.long()
describe(new_long_tensor)

type: torch.LongTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
import torch
new_int_tensor = torch.tensor([[1, 2, 3],
                               [4, 5, 6]], dtype=torch.int64)
describe(new_int_tensor)

type: torch.LongTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


Perform operations on tensors, such as `+`, `-`, `*`, `/`

In [15]:
import torch
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)
addition = tensor1 + tensor2
print(f'tensor1: {tensor1}')
print(f'tensor2: {tensor2}')
print(f'tensor1 + tensor2: {addition}')

tensor1: tensor([[0.3660, 0.7305, 0.9549],
        [0.1477, 0.7621, 0.3281]])
tensor2: tensor([[0.6026, 0.0147, 0.4730],
        [0.6191, 0.2263, 0.2617]])
tensor1 + tensor2: tensor([[0.9686, 0.7452, 1.4279],
        [0.7668, 0.9884, 0.5899]])


In [16]:
import torch
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)
addition = torch.add(tensor1, tensor2)
print(f'tensor1: {tensor1}')
print(f'tensor2: {tensor2}')
print(f'tensor1 + tensor2: {addition}')

tensor1: tensor([[0.4669, 0.2970, 0.3560],
        [0.2117, 0.8107, 0.2957]])
tensor2: tensor([[0.3626, 0.3754, 0.6631],
        [0.1906, 0.5737, 0.9186]])
tensor1 + tensor2: tensor([[0.8296, 0.6724, 1.0190],
        [0.4023, 1.3843, 1.2143]])


Use `index_select` for complex indexing and slicing  
Note: It is required to use `LongTensor` for the indices 

In [19]:
import torch
x = torch.arange(6).reshape(2, 3)
describe(x)

type: torch.LongTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [22]:
indices = torch.LongTensor([0, 0])
indexing_res = torch.index_select(x, dim=0, index=indices)
describe(indexing_res)

type: torch.LongTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [25]:
indices = torch.LongTensor([0, 1, 0])
indexing_res = torch.index_select(x, dim=1, index=indices)
describe(indexing_res)

type: torch.LongTensor
shape/size: torch.Size([2, 3])
values: 
tensor([[0, 1, 0],
        [3, 4, 3]])


To enable bookkeeping operations that can track the gradient at the tensor as well as the gradient function, set `requires_grad` Boolean flag to `True`

In [40]:
import torch
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x.requires_grad = True
print(x.grad is None)

True


In [41]:
y = (x + 2) * (x + 5) + 3
print(y.grad is None)

True


/Users/ivanchen/Desktop/pytorch_basics/venv/lib/python3.7/site-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [42]:
z = y.mean()
z.backward()
print(x.grad)

tensor([[1.5000, 1.8333, 2.1667],
        [2.5000, 2.8333, 3.1667]])


Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.

In [48]:
a = torch.rand(3, 3)
new_a = a.unsqueeze(0)
describe(new_a)

type: torch.FloatTensor
shape/size: torch.Size([1, 3, 3])
values: 
tensor([[[0.3911, 0.1255, 0.4797],
         [0.2515, 0.3408, 0.2092],
         [0.7939, 0.0024, 0.1961]]])


Remove the extra dimension you just added to the previous tensor.

In [49]:
new_a = a.squeeze(0)
describe(new_a)

type: torch.FloatTensor
shape/size: torch.Size([3, 3])
values: 
tensor([[0.3911, 0.1255, 0.4797],
        [0.2515, 0.3408, 0.2092],
        [0.7939, 0.0024, 0.1961]])


Create a random tensor of shape 5x3 in the interval [3, 7)

In [52]:
a = torch.rand(5, 3) * (7 - 3) + 3
describe(a)

type: torch.FloatTensor
shape/size: torch.Size([5, 3])
values: 
tensor([[4.4938, 5.1163, 6.0424],
        [5.3575, 5.2689, 5.8089],
        [4.0430, 4.0338, 6.2389],
        [4.1750, 6.8753, 6.1547],
        [3.0452, 3.9808, 6.3214]])


Create a tensor with values from a normal distribution (mean=0, std=1)

In [53]:
a = torch.rand(3, 3)
a.normal_()
describe(a)

type: torch.FloatTensor
shape/size: torch.Size([3, 3])
values: 
tensor([[-0.4377, -0.9724,  0.9319],
        [ 0.6033, -0.7209, -0.9570],
        [ 0.1374, -0.0873, -1.3255]])


Retrieve the indexes of all the nonzero elements in the tensor `torch.Tensor([1, 1, 1, 0, 1])`

In [55]:
a = torch.Tensor([1, 1, 1, 0, 1])
print(torch.nonzero(a))

tensor([[0],
        [1],
        [2],
        [4]])


../torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)


Create a random tensor of size (3,1) and then horizontally stack four copies together

In [56]:
a = torch.rand(3, 1)
new_a = torch.cat([a, a, a, a], dim=1)
describe(new_a)

type: torch.FloatTensor
shape/size: torch.Size([3, 4])
values: 
tensor([[0.1498, 0.1498, 0.1498, 0.1498],
        [0.4282, 0.4282, 0.4282, 0.4282],
        [0.4039, 0.4039, 0.4039, 0.4039]])


In [57]:
a = torch.rand(3, 1)
new_a = a.expand(3, 4)
describe(new_a)

type: torch.FloatTensor
shape/size: torch.Size([3, 4])
values: 
tensor([[0.2361, 0.2361, 0.2361, 0.2361],
        [0.8209, 0.8209, 0.8209, 0.8209],
        [0.4990, 0.4990, 0.4990, 0.4990]])


Return the batch matrix­matrix product of two three­dimensional matrices

In [59]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
mul_res = torch.bmm(a, b)
describe(mul_res)

type: torch.FloatTensor
shape/size: torch.Size([3, 4, 4])
values: 
tensor([[[0.9971, 1.0341, 1.2981, 0.9452],
         [1.1958, 1.4912, 1.3396, 1.3933],
         [1.4195, 1.6713, 1.7064, 1.6990],
         [0.6073, 1.1140, 1.2329, 1.0674]],

        [[0.6885, 0.9850, 0.6519, 1.1256],
         [1.1994, 1.4808, 1.4160, 2.0609],
         [0.9277, 1.2166, 1.0350, 1.6507],
         [0.6328, 0.5843, 0.8140, 1.1469]],

        [[0.6521, 1.1723, 1.1073, 0.9042],
         [1.0545, 1.7231, 1.9721, 1.5717],
         [0.6584, 1.1213, 0.9755, 1.0692],
         [0.4923, 0.8143, 0.8540, 0.7634]]])


Return the batch matrix­matrix product of a 3D matrix and a 2D matrix

In [65]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)
mul_res = torch.bmm(a, b.unsqueeze(0).expand(3, 5, 4))
describe(mul_res)

type: torch.FloatTensor
shape/size: torch.Size([3, 4, 4])
values: 
tensor([[[0.6901, 1.1699, 1.0093, 1.3746],
         [0.6617, 1.3787, 1.0042, 1.8279],
         [0.9285, 1.7178, 1.7306, 2.3472],
         [0.3412, 0.6219, 0.8230, 0.8462]],

        [[0.4935, 0.9394, 0.8550, 1.3942],
         [0.3636, 0.7419, 0.9118, 1.0552],
         [1.0275, 1.2564, 1.4255, 1.8872],
         [0.4990, 0.6942, 0.8994, 1.2455]],

        [[0.9105, 1.5298, 0.9645, 2.0362],
         [0.5278, 1.1272, 0.9263, 1.5801],
         [0.7226, 1.4677, 1.3473, 2.0111],
         [0.8603, 1.4163, 1.1667, 1.7265]]])
